# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - qlend-sandbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://qlend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5eb80a78d6db42ecb4f24e987877c38f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_49501963aa324f7baf320a4e757b9461 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: qlend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5eb80a78d6db42ecb4f24e987877c38f }}/qlend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'qlend-sandbox'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c69edcc9d524e89993122e597ce9226 }}
        images: 'qlend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5eb80a78d6db42ecb4f24e987877c38f }}/qlend:${{ github.sha }}'